# Generated by Django 2.2.1 on 2019-05-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('picture', models.ImageField(blank=True, upload_to='posts/pictures')),
                ('video', models.FileField(blank=True, upload_to='posts/videos')),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Member')),
            ],
        ),
    ]
