# Generated by Django 2.2.1 on 2019-05-05 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190505_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
