# Generated by Django 2.2.1 on 2019-05-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_content', models.TextField(max_length=5000)),
                ('notify_time', models.DateTimeField(auto_now_add=True)),
                ('notifying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Member')),
            ],
        ),
    ]
