# Generated by Django 2.2.1 on 2019-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='church officials/images')),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('photo', models.ImageField(upload_to='developers/images')),
                ('languages', models.TextField()),
                ('contributions', models.TextField()),
            ],
        ),
    ]
