# Generated by Django 2.2.1 on 2019-06-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_churchofficial_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Tools/images')),
                ('use', models.TextField()),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
