# Generated by Django 2.2.2 on 2019-09-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_for', models.CharField(choices=[('mission_statement', 'mission_statement'), ('vision', 'vision')], max_length=50)),
                ('content', models.TextField()),
                ('church_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ChurchDetail')),
            ],
        ),
    ]
