# Generated by Django 2.2.2 on 2019-09-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_churchdetail_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchofficial',
            name='church_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.ChurchDetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchofficial',
            name='small_bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='churchofficial',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='churchofficial',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('church_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ChurchDetail')),
            ],
        ),
    ]
