# Generated by Django 2.2.2 on 2019-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190922_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetail',
            name='mission_statement',
            field=models.TextField(default='Hello World'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchdetail',
            name='vision_statement',
            field=models.TextField(default='Hello user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
