# Generated by Django 2.2.2 on 2019-09-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190922_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetail',
            name='email',
            field=models.EmailField(default='info@hfconline.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=14)),
                ('church_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ChurchDetail')),
            ],
        ),
    ]
