# Generated by Django 2.2.2 on 2019-09-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='church_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.ChurchDetail'),
            preserve_default=False,
        ),
    ]
