# Generated by Django 2.2.2 on 2019-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_service_church_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetail',
            name='account_no',
            field=models.CharField(default=1234567891, max_length=14),
            preserve_default=False,
        ),
    ]
