# Generated by Django 2.2.2 on 2019-09-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_churchdetail_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetail',
            name='account_bank',
            field=models.CharField(default='Access Bank Plc', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchdetail',
            name='account_name',
            field=models.CharField(default='Pius Marshal', max_length=20),
            preserve_default=False,
        ),
    ]
