# Generated by Django 2.2.2 on 2019-09-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190922_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='about/images')),
                ('church_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ChurchDetail')),
            ],
        ),
    ]
